# Generated by Django 2.1.5 on 2019-04-23 15:20

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='trello_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='trello_sync',
            field=models.BooleanField(default=False, verbose_name='Синхронизировать'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Введите набор тэгов для задачи, разделяя их запятой', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
