# Generated by Django 2.1.5 on 2019-04-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tagcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prio_level', models.PositiveIntegerField(default=1)),
                ('prio_count', models.PositiveIntegerField(db_index=True, default=0)),
            ],
        ),
    ]
