# Generated by Django 2.1.5 on 2019-04-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_prioritycount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioritycount',
            name='prio_level',
            field=models.PositiveIntegerField(choices=[(1, 'Высокий приоритет'), (2, 'Средний приоритет'), (3, 'Низкий приоритет')], default=1),
        ),
    ]
